In [1]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import plotly.express as px
# import seaborn as sns
# import plotnine

In [2]:
# %matplotlib notebook

In [3]:
#df_worldbank = pd.read_csv('data/API_EN.ATM.CO2E.KT_DS2_en_csv_v2_2708702.csv', skiprows=4)
#df_meta1 = pd.read_csv('data/Metadata_Country_API_EN.ATM.CO2E.KT_DS2_en_csv_v2_2708702.csv')
#df_meta2 = pd.read_csv('data/Metadata_Indicator_API_EN.ATM.CO2E.KT_DS2_en_csv_v2_2708702.csv')
df = pd.read_csv('data/owid-co2-data.csv')

In [4]:
# select important columns
df = df[['iso_code',
 'country',
 'year',
 'co2',
 'co2_growth_prct',
 'co2_growth_abs',
 'co2_per_capita',
 'co2_per_gdp',
 'share_global_co2',
 'cumulative_co2',
 'share_global_cumulative_co2',
 'ghg_per_capita',
 'methane',
 'methane_per_capita',
 'nitrous_oxide',
 'nitrous_oxide_per_capita',
 'primary_energy_consumption',
 'energy_per_capita',
 'energy_per_gdp',
 'population',
 'gdp']]

In [5]:
df

,iso_code,country,year,co2,co2_growth_prct,co2_growth_abs,co2_per_capita,co2_per_gdp,share_global_co2,cumulative_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,primary_energy_consumption,energy_per_capita,energy_per_gdp,population,gdp
0,AFG,Afghanistan,1949,0.015,NaN,NaN,0.002,NaN,0.000,0.015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7663783.0,NaN
1,AFG,Afghanistan,1950,0.084,475.000,0.070,0.011,0.004,0.001,0.099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7752000.0,1.949480e+10
2,AFG,Afghanistan,1951,0.092,8.696,0.007,0.012,0.005,0.001,0.191,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7840000.0,2.006385e+10
3,AFG,Afghanistan,1952,0.092,NaN,NaN,0.012,0.004,0.001,0.282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7936000.0,2.074235e+10
4,AFG,Afghanistan,1953,0.106,16.000,0.015,0.013,0.005,0.002,0.388,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8040000.0,2.201546e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23703,ZWE,Zimbabwe,2015,12.170,1.653,0.198,0.881,0.486,0.035,726.480,...,4.885,11.87,0.859,6.68,0.484,NaN,NaN,NaN,13815000.0,2.503057e+10
23704,ZWE,Zimbabwe,2016,10.815,-11.139,-1.356,0.771,0.430,0.031,737.295,...,4.703,11.92,0.850,6.55,0.467,NaN,NaN,NaN,14030000.0,2.515176e+10
23705,ZWE,Zimbabwe,2017,10.247,-5.251,-0.568,0.720,NaN,0.029,747.542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14237000.0,NaN
23706,ZWE,Zimbabwe,2018,11.341,10.674,1.094,0.785,NaN,0.031,758.882,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14439000.0,NaN
23707,ZWE,Zimbabwe,2019,10.374,-8.521,-0.966,0.708,NaN,0.028,769.256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14645000.0,NaN

In [19]:
df2019 = df[df['year']==2019]

In [20]:
df2019

,iso_code,country,year,co2,co2_growth_prct,co2_growth_abs,co2_per_capita,co2_per_gdp,share_global_co2,cumulative_co2,...,ghg_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,primary_energy_consumption,energy_per_capita,energy_per_gdp,population,gdp
70,AFG,Afghanistan,2019,10.720,2.561,0.268,0.282,NaN,0.029,181.376,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.804200e+07,NaN
206,NaN,Africa,2019,1434.873,1.603,22.641,1.121,NaN,3.937,45881.556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.308064e+09,NaN
293,ALB,Albania,2019,5.579,3.258,0.176,1.936,NaN,0.015,282.495,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.881000e+06,NaN
397,DZA,Algeria,2019,171.707,4.502,7.398,3.988,NaN,0.471,4445.486,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.305300e+07,NaN
427,AND,Andorra,2019,0.470,1.354,0.006,6.110,NaN,0.001,14.543,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.700000e+04,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23180,WLF,Wallis and Futuna Islands,2019,0.029,6.541,0.002,NaN,NaN,0.000,0.484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23450,OWID_WRL,World,2019,36441.388,0.060,21.676,4.724,NaN,100.000,1652920.394,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.713468e+09,NaN
23520,YEM,Yemen,2019,10.255,3.115,0.310,0.352,NaN,0.028,615.411,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.916200e+07,NaN
23590,ZMB,Zambia,2019,6.720,-3.025,-0.210,0.376,NaN,0.018,234.568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.786100e+07,NaN
23707,ZWE,Zimbabwe,2019,10.374,-8.521,-0.966,0.708,NaN,0.028,769.256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.464500e+07,NaN